# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('played', models.IntegerField()),
                ('points', models.IntegerField()),
                ('start_day_position', models.IntegerField()),
                ('won', models.IntegerField()),
                ('away_against', models.IntegerField()),
                ('away_drawn', models.IntegerField()),
                ('away_for', models.IntegerField()),
                ('away_lost', models.IntegerField()),
                ('away_played', models.IntegerField()),
                ('away_points', models.IntegerField()),
                ('away_position', models.IntegerField()),
                ('away_won', models.IntegerField()),
                ('home_against', models.IntegerField()),
                ('home_drawn', models.IntegerField()),
                ('home_for', models.IntegerField()),
                ('home_lost', models.IntegerField()),
                ('home_played', models.IntegerField()),
                ('home_points', models.IntegerField()),
                ('home_position', models.IntegerField()),
                ('home_won', models.IntegerField()),
            ],
        ),
    ]
