# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_auto_20151203_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstanding',
            options={},
        ),
    ]
