# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_auto_20151203_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstanding',
            old_name='competition',
            new_name='competition_id',
        ),
        migrations.RenameField(
            model_name='teamstanding',
            old_name='season',
            new_name='season_id',
        ),
        migrations.AlterUniqueTogether(
            name='teamstanding',
            unique_together=set([('source_timestamp', 'team_id', 'competition_id', 'season_id')]),
        ),
    ]
